### ISSUE TITLE
How to install in travis

### ISSUE THREAD

**Issue by AlexSwensen** [naftulikay/travis-pls#6]
I tried to add the package by doing `pip install travis-pls`, only to realize that it wasn't properly being published. 😕

For now I am installing using:
```yml
install: pip install git+https://github.com/naftulikay/travis-pls
```

But that is not the most elegant solution. Any chance this can get added to pypi?

**Comment by AlexSwensen** [comment]
Oops! never-mind. I just realized it is on pypi under `travispls`

Maybe we should get this added to the readme. :-)

**Comment by naftulikay** [comment]
Unfortunately, PyPI's uptime and reliability are terrible, which is why this is still the recommended way to get `travis-pls`. If you'd like to save a step, just shove this URL into `requirements.txt` and Travis should pick it up automatically and install it on build.

**`requirements.txt`**

```
git+https://github.com/naftulikay/travis-pls
```

Actually, it does seem that PyPI has the latest: https://pypi.org/project/travispls/

I'd still recommend installing using the Git URL. Any time I have actually depended on PyPI in production, I have suffered.

**Comment by AlexSwensen** [comment]
@naftulikay Hmm, while i can see your point, i (subjectively) don't think most of the python ecosystem works that way at-present. Perhaps it would be better to leave a description to that effect? At least at that point it's easier for people to use the package, and at that point it is their choice.

**Comment by naftulikay** [comment]
Yup, totally. PRs are welcome for updating the README. It also seems that something took down the dolan 'travis pls' image, which is unfortunate. I'm knee-deep in a slew of other projects right now.

**Comment by AlexSwensen** [comment]
@naftulikay Happy to. 😄 

Best of luck with your projects & happy new year!
